// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: protos/messenger.proto

package messenger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessengerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessengerRequest) Reset() {
	*x = MessengerRequest{}
	mi := &file_protos_messenger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessengerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessengerRequest) ProtoMessage() {}

func (x *MessengerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messenger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessengerRequest.ProtoReflect.Descriptor instead.
func (*MessengerRequest) Descriptor() ([]byte, []int) {
	return file_protos_messenger_proto_rawDescGZIP(), []int{0}
}

func (x *MessengerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MessengerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessengerResponse) Reset() {
	*x = MessengerResponse{}
	mi := &file_protos_messenger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessengerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessengerResponse) ProtoMessage() {}

func (x *MessengerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messenger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessengerResponse.ProtoReflect.Descriptor instead.
func (*MessengerResponse) Descriptor() ([]byte, []int) {
	return file_protos_messenger_proto_rawDescGZIP(), []int{1}
}

func (x *MessengerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessengerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MessengerResponse) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

var File_protos_messenger_proto protoreflect.FileDescriptor

const file_protos_messenger_proto_rawDesc = "" +
	"\n" +
	"\x16protos/messenger.proto\x12\tmessenger\"\"\n" +
	"\x10MessengerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"I\n" +
	"\x11MessengerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age2X\n" +
	"\x10MessengerService\x12D\n" +
	"\aGetUser\x12\x1b.messenger.MessengerRequest\x1a\x1c.messenger.MessengerResponseBKZIgithub.com/I-Frostbyte/Learning-Curve/gRPC/grpc-in-go/protobufs/messengerb\x06proto3"

var (
	file_protos_messenger_proto_rawDescOnce sync.Once
	file_protos_messenger_proto_rawDescData []byte
)

func file_protos_messenger_proto_rawDescGZIP() []byte {
	file_protos_messenger_proto_rawDescOnce.Do(func() {
		file_protos_messenger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_messenger_proto_rawDesc), len(file_protos_messenger_proto_rawDesc)))
	})
	return file_protos_messenger_proto_rawDescData
}

var file_protos_messenger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_messenger_proto_goTypes = []any{
	(*MessengerRequest)(nil),  // 0: messenger.MessengerRequest
	(*MessengerResponse)(nil), // 1: messenger.MessengerResponse
}
var file_protos_messenger_proto_depIdxs = []int32{
	0, // 0: messenger.MessengerService.GetUser:input_type -> messenger.MessengerRequest
	1, // 1: messenger.MessengerService.GetUser:output_type -> messenger.MessengerResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_messenger_proto_init() }
func file_protos_messenger_proto_init() {
	if File_protos_messenger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_messenger_proto_rawDesc), len(file_protos_messenger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_messenger_proto_goTypes,
		DependencyIndexes: file_protos_messenger_proto_depIdxs,
		MessageInfos:      file_protos_messenger_proto_msgTypes,
	}.Build()
	File_protos_messenger_proto = out.File
	file_protos_messenger_proto_goTypes = nil
	file_protos_messenger_proto_depIdxs = nil
}
